// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {ports} from '../models';
import {workspace} from '../models';

export function AddWorkspace(arg1:string):Promise<api.DiscoverResult>;

export function ApplyDiscovery(arg1:string,arg2:Array<string>,arg3:Array<string>):Promise<void>;

export function BufferLog(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CheckBuilds(arg1:string):Promise<api.BuildCheckResult>;

export function DiscoverWorkspace(arg1:string):Promise<api.DiscoverDiff>;

export function GetEnv(arg1:string):Promise<Record<string, Array<api.EnvVar>>>;

export function GetLogs(arg1:string,arg2:string,arg3:number):Promise<Array<api.LogLine>>;

export function GetPorts():Promise<Array<ports.PortEntry>>;

export function GetSettings():Promise<api.Settings>;

export function GetWorkspace(arg1:string):Promise<api.WorkspaceDetail>;

export function ListWorkspaces():Promise<Array<api.WorkspaceInfo>>;

export function PreviewManifest(arg1:workspace.Manifest):Promise<string>;

export function RemoveWorkspace(arg1:string):Promise<void>;

export function ResetPorts():Promise<void>;

export function RestartService(arg1:string,arg2:string):Promise<void>;

export function SaveManifest(arg1:string,arg2:workspace.Manifest):Promise<void>;

export function SaveSettings(arg1:api.Settings):Promise<void>;

export function SetEmitter(arg1:api.EventEmitter):Promise<void>;

export function StartService(arg1:string,arg2:string):Promise<void>;

export function StartWorkspace(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function StopService(arg1:string,arg2:string):Promise<void>;

export function StopWorkspace(arg1:string):Promise<void>;
