package envgen

import (
	"bytes"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
	"text/template"

	"github.com/andybarilla/rook/internal/workspace"
)

type templateData struct {
	Port map[string]string
	Host map[string]string
}

func ResolveTemplates(env map[string]string, portMap map[string]int, devcontainer bool) (map[string]string, error) {
	return ResolveTemplatesWithServices(env, portMap, devcontainer, nil)
}

func ResolveTemplatesWithServices(env map[string]string, portMap map[string]int, devcontainer bool, services map[string]workspace.Service) (map[string]string, error) {
	data := templateData{
		Port: make(map[string]string),
		Host: make(map[string]string),
	}

	for name, port := range portMap {
		if devcontainer && services != nil {
			if svc, ok := services[name]; ok && svc.IsContainer() && len(svc.Ports) > 0 {
				data.Port[name] = strconv.Itoa(svc.Ports[0])
			} else {
				data.Port[name] = strconv.Itoa(port)
			}
		} else {
			data.Port[name] = strconv.Itoa(port)
		}

		if devcontainer {
			data.Host[name] = name
		} else {
			data.Host[name] = "localhost"
		}
	}

	result := make(map[string]string, len(env))
	for k, v := range env {
		if !strings.Contains(v, "{{") {
			result[k] = v
			continue
		}

		tmpl, err := template.New(k).Parse(v)
		if err != nil {
			return nil, fmt.Errorf("parsing template for %s: %w", k, err)
		}

		var buf bytes.Buffer
		if err := tmpl.Execute(&buf, data); err != nil {
			return nil, fmt.Errorf("executing template for %s: %w", k, err)
		}
		result[k] = buf.String()
	}

	return result, nil
}

// ResolveWithHostMap resolves templates using explicit host and port maps.
// This is used for container-to-container networking where hosts are container
// names and ports are internal container ports.
func ResolveWithHostMap(env map[string]string, portMap map[string]int, hostMap map[string]string) (map[string]string, error) {
	data := templateData{
		Port: make(map[string]string),
		Host: make(map[string]string),
	}

	for name, host := range hostMap {
		data.Host[name] = host
	}
	for name, port := range portMap {
		data.Port[name] = strconv.Itoa(port)
	}

	result := make(map[string]string, len(env))
	for k, v := range env {
		if !strings.Contains(v, "{{") {
			result[k] = v
			continue
		}

		tmpl, err := template.New(k).Parse(v)
		if err != nil {
			return nil, fmt.Errorf("parsing template for %s: %w", k, err)
		}

		var buf bytes.Buffer
		if err := tmpl.Execute(&buf, data); err != nil {
			return nil, fmt.Errorf("executing template for %s: %w", k, err)
		}
		result[k] = buf.String()
	}

	return result, nil
}

// ResolveFileTemplate resolves {{.Host.x}} and {{.Port.x}} templates in a
// file's content string. Used for config files like Caddyfile that need
// container names and ports resolved before mounting.
func ResolveFileTemplate(content string, portMap map[string]int, hostMap map[string]string) (string, error) {
	data := templateData{
		Port: make(map[string]string),
		Host: make(map[string]string),
	}
	for name, host := range hostMap {
		data.Host[name] = host
	}
	for name, port := range portMap {
		data.Port[name] = strconv.Itoa(port)
	}

	tmpl, err := template.New("file").Parse(content)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing template: %w", err)
	}
	return buf.String(), nil
}

func WriteEnvFile(path string, vars map[string]string) error {
	keys := make([]string, 0, len(vars))
	for k := range vars {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var buf bytes.Buffer
	buf.WriteString("# Generated by Rook — do not edit\n")
	for _, k := range keys {
		fmt.Fprintf(&buf, "%s=%s\n", k, vars[k])
	}

	return os.WriteFile(path, buf.Bytes(), 0644)
}
