// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWorkspace(arg1) {
  return window['go']['api']['WorkspaceAPI']['AddWorkspace'](arg1);
}

export function ApplyDiscovery(arg1, arg2, arg3) {
  return window['go']['api']['WorkspaceAPI']['ApplyDiscovery'](arg1, arg2, arg3);
}

export function BufferLog(arg1, arg2, arg3) {
  return window['go']['api']['WorkspaceAPI']['BufferLog'](arg1, arg2, arg3);
}

export function CheckBuilds(arg1) {
  return window['go']['api']['WorkspaceAPI']['CheckBuilds'](arg1);
}

export function DiscoverWorkspace(arg1) {
  return window['go']['api']['WorkspaceAPI']['DiscoverWorkspace'](arg1);
}

export function GetEnv(arg1) {
  return window['go']['api']['WorkspaceAPI']['GetEnv'](arg1);
}

export function GetLogs(arg1, arg2, arg3) {
  return window['go']['api']['WorkspaceAPI']['GetLogs'](arg1, arg2, arg3);
}

export function GetPorts() {
  return window['go']['api']['WorkspaceAPI']['GetPorts']();
}

export function GetSettings() {
  return window['go']['api']['WorkspaceAPI']['GetSettings']();
}

export function GetWorkspace(arg1) {
  return window['go']['api']['WorkspaceAPI']['GetWorkspace'](arg1);
}

export function ListWorkspaces() {
  return window['go']['api']['WorkspaceAPI']['ListWorkspaces']();
}

export function PreviewManifest(arg1) {
  return window['go']['api']['WorkspaceAPI']['PreviewManifest'](arg1);
}

export function RemoveWorkspace(arg1) {
  return window['go']['api']['WorkspaceAPI']['RemoveWorkspace'](arg1);
}

export function ResetPorts() {
  return window['go']['api']['WorkspaceAPI']['ResetPorts']();
}

export function RestartService(arg1, arg2) {
  return window['go']['api']['WorkspaceAPI']['RestartService'](arg1, arg2);
}

export function SaveManifest(arg1, arg2) {
  return window['go']['api']['WorkspaceAPI']['SaveManifest'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['api']['WorkspaceAPI']['SaveSettings'](arg1);
}

export function SetEmitter(arg1) {
  return window['go']['api']['WorkspaceAPI']['SetEmitter'](arg1);
}

export function StartService(arg1, arg2) {
  return window['go']['api']['WorkspaceAPI']['StartService'](arg1, arg2);
}

export function StartWorkspace(arg1, arg2, arg3) {
  return window['go']['api']['WorkspaceAPI']['StartWorkspace'](arg1, arg2, arg3);
}

export function StopService(arg1, arg2) {
  return window['go']['api']['WorkspaceAPI']['StopService'](arg1, arg2);
}

export function StopWorkspace(arg1) {
  return window['go']['api']['WorkspaceAPI']['StopWorkspace'](arg1);
}
