// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {databases} from '../models';
import {registry} from '../models';

export function AddSite(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function CheckRuntimes():Promise<Array<core.RuntimeStatus>>;

export function DatabaseServices():Promise<Array<databases.ServiceInfo>>;

export function DetectSiteVersions(arg1:string):Promise<Record<string, string>>;

export function InstallRuntime(arg1:string,arg2:string):Promise<void>;

export function ListSites():Promise<Array<registry.Site>>;

export function MiseStatus():Promise<core.MiseInfo>;

export function RemoveSite(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function StartDatabase(arg1:string):Promise<void>;

export function StopDatabase(arg1:string):Promise<void>;
