// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSite(arg1:string, arg2:string, arg3:string, arg4:boolean):Promise<void>;

export function ListSites():Promise<Array<any>>;

export function RemoveSite(arg1:string):Promise<void>;
